In [18]:
#Question 1
import numpy as np

tab = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(tab.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [47]:
#Question 2
import numpy as np

tab = np.array([[1,2,3], [4,5,6], [7,8,9]])
tr = np.trace(tab)
print(tab)
print("la somme des élemens diagonaux demandé est :", tr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
la somme des élemens diagonaux demandé est : 15


In [33]:
#Question 3
import numpy as np

tab = np.array([[1,2], [3,5]])
d = tab[tab>2]
print(f"{d}")

[3 5]


In [35]:
#Question 4
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,2,3], [4,5,6], [7,8,9]])

C = np.add(A,B)
print("la somme de A et B est : C = ")
print(C)

la somme de A et B est : C = 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [46]:
#Question 5
import numpy as np

tab = np.array([[4,5,6], [7,8,9],[1,2,3], [19,3,7]])
mean_line = np.mean(tab, axis = 1)
print(tab)
taille = tab.shape
def takeFirst(elem):
   return elem[0]
for i in range(takeFirst(taille)):
    print("la moyenne de la ligne",i,"est",mean_line[i])

[[ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]
 [19  3  7]]
la moyenne de la ligne 0 est 5.0
la moyenne de la ligne 1 est 8.0
la moyenne de la ligne 2 est 2.0
la moyenne de la ligne 3 est 9.666666666666666
